# Generated by Django 2.1 on 2020-05-15 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field=224, upload_to='images/', width_field=224)),
                ('cupboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cupboard')),
            ],
        ),
        migrations.CreateModel(
            name='m_ClassField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='dress',
            name='prediction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.m_ClassField'),
        ),
    ]
